### ISSUE TITLE
Error moving /etc/lighttp/lighttpd.conf in fresh container on arm

### ISSUE THREAD

**Issue by aptalca** [pi-hole/docker-pi-hole#308]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Fresh container on arm fails with error: mv: cannot move '/etc/lighttpd/lighttpd.conf' to a subdirectory of itself, '/etc/lighttpd/lighttpd.conf.orig'`
## Expected Behavior

Should start up
## Actual Behavior

Exits 1 and container is brought down
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
`docker create --name=ph -p 53:53/tcp -p 53:53/udp -p 80:80 -p 443:443 -e ServerIP="1
92.168.1.34" -v /storage/ph/pihole:/etc/pihole -v /storage/ph/dnsmasq.d:/etc/dnsmasq.d pihole/pihole:v4.0_armhf`

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Libreelec
* Docker Version: 1.13.1
* Hardware architecture:  arm s905x

Full docker log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker pihole/pihole
  [i] Existing PHP installation detected : PHP version 7.0.30-0+deb9u1
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
mv: cannot move '/etc/lighttpd/lighttpd.conf' to a subdirectory of itself, '/etc/lighttpd/lighttpd.conf.orig'
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by diginc** [comment]
Could also try running without volumes to see if that eliminates the error?  Not permanently but just as a test of docker.

I've seen a few issues like this now but when we dig into it the error message is misleading - in this error's case, [neither /etc/lighttpd/lighttpd.conf or /etc/lighttpd/lighttpd.conf.orig is a directory](https://www.reddit.com/r/pihole/comments/9518ef/error_creating_a_container_using_40_armhfaarch64/) when inspected closer.  Strange misleading errors we've spent a lot of time looking into have often been solved just by upgrading docker.

If I wanted to reproduce your setup would I just grab [libelec](https://libreelec.tv/downloads/) and [a docker add-on](https://forum.libreelec.tv/thread/6721-linuxserver-io-docker-addons-and-general-docker-info/) ?

**Comment by aptalca** [comment]
That was libreelec 8.2.3.1, the latest stable
Kernel is 3.14.29

I also tested the image in libreelec 8.2.3.1 running on x86_64 with kernel 4.11.12 with docker 1.13.1 and it works fine.

It is likely related to the kernel or the arch.

Can you point me to the line of code where that specific mv operation is performed?

**Comment by aptalca** [comment]
If you'd like to recreate the error, you would need to install libreelec on an amlogic device (s905x or related) and install the docker service addon from the libreelec repo. Then you can use docker in commandline, no need for other addons.

**Comment by ssplatt** [comment]
i'm getting this same error with the aarch64 build, kubernetes, and no volumes. I was trying to migrate off the older repo (diginc/pi-hole-multiarch:debian_aarch64)

**Comment by Vashiru** [comment]
I can confirm this is still an issue on pihole/pihole:v4.0_armhf. Clean install (my first time ever running this).

**Comment by Vashiru** [comment]
I did some experimenting based on the Reddit post that @diginc mentioned. Since it seems to imply that the only reason we copy lighttpd.conf over to lighttpd.conf.orig is "back-up purposes". Because it appears we're building our own config anyway, I went ahead to see what would happen if I'd just remove it before it would even attempt the back-up... Suddenly I could start the container and run everything.

All I've done is modify start.sh as follows:
```
echo " ::: Starting docker specific setup for docker pihole/pihole"
validate_env || exit 1
rm /etc/lighttpd/lighttpd.conf
prepare_configs
```
For those that don't want to experiment themselves, I've published this very crude fix for the `arm` and `aarch64` images over at: https://hub.docker.com/r/vashiru/pihole/

Note 1: I didn't get this to work with the port forwarding, it gave me config issues. Since I wanted to run it at as --net=host I've not further looked into it. It might work, but no guarantees.
Note 2: I don't plan on supporting this image and probably will discard it once the issue get fixed on this repo.

**Comment by CirConFleX** [comment]
Hi Vashiru, i can't download your image with _docker pull vashiru/pihole_. I tried also _docker pull vashiru/pihole:aarch64_ and _docker pull vashiru/pihole:v4.0_aarch64_ but no luck. Can you help me please ?

**Comment by rene-demonsters** [comment]
> Hi Vashiru, i can't download your image with _docker pull vashiru/pihole_. I tried also _docker pull vashiru/pihole:aarch64_ and _docker pull vashiru/pihole:v4.0_aarch64_ but no luck. Can you help me please ?

@CirConFleX That's because I labeled them differently, see: https://hub.docker.com/r/vashiru/pihole/tags/
You're looking for `vashiru/pihole:lighttpd_monkeypatch_aarch64` and for the 32 bit version that would be `vashiru/pihole:lighttpd_monkeypatch_armhf`. Good luck!

**Comment by ssplatt** [comment]
the comments saying permissions were the issue drove me to finally setting up volume mounts in kubernetes, which allows the container to get a little further.  (odroid c2) arm64, kubernetes 1.12.2, docker 18.05.

```
        volumeMounts:
        - mountPath: /etc/pihole
          name: piholeconf
        - mountPath: /etc/dnsmasq.d
          name: dnsmasqconf
        - mountPath: /etc/lighttpd
          name: lighttpdconf
      volumes:
      - name: piholeconf
        hostPath:
          path: /persist/pihole/conf
      - name: dnsmasqconf
        hostPath:
          path: /persist/pihole/dnsmasqd
      - name: lighttpdconf
        hostPath:
          path: /persist/pihole/lighttpd
```
I created the `lighttpd/conf-enabled/10-fastcgi.conf` and `lighttpd/conf-enabled/15-fastcgi-php.conf`. I'm still getting some other errors but i don't think they are related to this issue. ("can't bind to port: 127.0.0.1 80 Address already in use. Stopping lighttpd. lighttpd: no process found")

**Comment by punkidow** [comment]
@Vashiru 
I had been using your image for a few months without any problems, but today it wouldnt start: 
```
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] 01-resolver-resolv: applying... ,
[fix-attrs.d] 01-resolver-resolv: exited 0.,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 20-start.sh: executing... ,
 ::: Starting docker specific setup for docker pihole/pihole,
rm: cannot remove '/etc/lighttpd/lighttpd.conf': No such file or directory,
[cont-init.d] 20-start.sh: exited 1.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
```

**Comment by freeandroid** [comment]
Workaround for LibreELEC; (mostly put here so I don't forget, but might help others :) 
 
```
# docker cp pihole:/start.sh .
# nano start.sh
``` 

add line rm /etc/lighttpd/lighttpd.conf, just like Vashiru mentioned above;

```
echo " ::: Starting docker specific setup for docker pihole/pihole"
validate_env || exit 1
rm /etc/lighttpd/lighttpd.conf
prepare_configs
```

save the file then run;

```
# docker cp start.sh pihole:/start.sh
# docker restart pihole
```

**Comment by punkidow** [comment]
> Workaround for LibreELEC; (mostly put here so I don't forget, but might help others :)
> 
> ```
> # docker cp pihole:/start.sh .
> # nano start.sh
> ```
> add line rm /etc/lighttpd/lighttpd.conf, just like Vashiru mentioned above;
> 
> ```
> echo " ::: Starting docker specific setup for docker pihole/pihole"
> validate_env || exit 1
> rm /etc/lighttpd/lighttpd.conf
> prepare_configs
> ```
> save the file then run;
> 
> ```
> # docker cp start.sh pihole:/start.sh
> # docker restart pihole
> ```

Thank you so much for the extremely noob friendly guide. I can confirm that it works even on the latest 4.2.2 pihole image.

I have a question though: Is the start.sh file inside the image itself? And If the image is updated (by watchtower for example), will i have to do this again?

**Comment by freeandroid** [comment]
Yes, we copy the start.sh from and then back into the image. Yes, I had to do this again after updating because you have to pull the new image and toss away the old one.  See the upgrade section here for more details: https://hub.docker.com/r/diginc/pi-hole/

**Comment by diginc** [comment]
I threw together a quick fix in [bash_functions.sh](https://gist.github.com/diginc/6515f2920227789885ed513da6023428), let me know if it works and I'll get it released to make upgrading more convenient.

```
wget https://gist.githubusercontent.com/diginc/6515f2920227789885ed513da6023428/raw/1a3baae0f88dc5e1d5b05006be9d84b91365edcf/bash_functions_issue_308.sh
docker cp bash_functions_issue_308.sh pihole:/bash_functions.sh
docker restart pihole
```

**Comment by punkidow** [comment]
Alright so i just tried 
> wget https://gist.githubusercontent.com/diginc/6515f2920227789885ed513da6023428/raw/1a3baae0f88dc5e1d5b05006be9d84b91365edcf/bash_functions_issue_308.sh
> docker cp bash_functions_issue_308.sh pihole:/bash_functions.sh
> docker restart pihole
> ```

And i can confirm that it does indeed work. I pulled a new image, tried it without doing anything first, and got the lighttpd error, same as before. I ran these 3 commands and voila, it works!

**Comment by ngodber** [comment]
Hi @diginc I know this is an old issue but it would be great to get this fixed for those of us stuck on the old kernel 3.x kernels. Not sure if the upgrade patch was ever included but I assume the manual change to the imagine is still required. Any chance of getting the image itself to have a logic to check Kernel. I'm running latest CE arm64
![image](https://user-images.githubusercontent.com/11834846/105566589-ad4e9880-5d78-11eb-89c4-02f312263e4c.png)
