### ISSUE TITLE
`REPLY_ADDR*` should be documented

### ISSUE THREAD

**Issue by scara** [pi-hole/docker-pi-hole#919]
This is a "**Bug**"

## Details
https://github.com/pi-hole/docker-pi-hole/pull/902 added `REPLY_ADDR*` to improve the FTLDNS configuration when running it within Docker: it should be documented, guessing into the [_Recommended Variables_](https://github.com/pi-hole/docker-pi-hole/tree/1a7bfdc2ee0558d1b184190895a85cdf9fbb7e35#environment-variables) section.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar

**Comment by PromoFaux** [comment]
Ah yes, it was missed. Would you like to PR it?

**Comment by scara** [comment]
Hi @PromoFaux:
> Would you like to PR it?

Yes, will do.

HTH,
Matteo

**Comment by dschaper** [comment]
FWIW, that variable is set when you use the `ServerIP` environment variable.

**Comment by dschaper** [comment]
https://github.com/pi-hole/docker-pi-hole/pull/902

**Comment by PromoFaux** [comment]
OH. Yes, of course.. that's why it's not in the Readme. Thanks @dschaper 

@scara belay that PR

**Comment by scara** [comment]
Thanks @dschaper!
I'm not familiar with Pi-hole code at all: apologies for the noise 😊.

For the record: `changeFTLsetting` is implemented [here](https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/advanced/Scripts/webpage.sh#L73).

I still wonder if the change in https://github.com/pi-hole/docker-pi-hole/pull/902 should be reported in the README.
Now `ServerIP` is described as:
| Variable | Default | Value | Description |
| -------- | ------- | ----- | ---------- |
| `ServerIP` | unset | `<Host's IP>` | Set to your server's LAN IP, used by web block modes and lighttpd bind address

which should be IMHO updated to tell about FTL REPLY setting will be affected too - and for `ServerIPv6` too.

Is
> lighttpd bind address

still appropriate?

I'm not familiar with the Pi-hole code but the [recent changes](https://github.com/pi-hole/docker-pi-hole/pull/902/files#diff-65a5db1ae8f8e01ebdbbfafcf4e24618ad7cffe036bba92dce1390383e5c73e5L80) suggest to me something like:
``` diff
diff --git a/start.sh b/start.sh
index 603cec3..bb79c6a 100755
--- a/start.sh
+++ b/start.sh
@@ -73,6 +73,7 @@ prepare_configs

 [ -n "${PIHOLE_INTERFACE}" ] && change_setting "PIHOLE_INTERFACE" "$PIHOLE_INTERFACE"
 [ -n "${IPV4_ADDRESS}" ] && change_setting "IPV4_ADDRESS" "$IPV4_ADDRESS"
+[ -n "${IPV6_ADDRESS}" ] && change_setting "IPV6_ADDRESS" "$IPV6_ADDRESS"
 [ -n "${INSTALL_WEB_SERVER}" ] && change_setting "INSTALL_WEB_SERVER" "$INSTALL_WEB_SERVER"
 [ -n "${INSTALL_WEB_INTERFACE}" ] && change_setting "INSTALL_WEB_INTERFACE" "$INSTALL_WEB_INTERFACE"
 [ -n "${LIGHTTPD_ENABLED}" ] && change_setting "LIGHTTPD_ENABLED" "$LIGHTTPD_ENABLED"
```
and to avoid regressions on past configurations I suggest to restore even:
``` diff
diff --git a/start.sh b/start.sh
index 603cec3..fbb6665 100755
--- a/start.sh
+++ b/start.sh
@@ -76,6 +76,8 @@ prepare_configs
 [ -n "${INSTALL_WEB_SERVER}" ] && change_setting "INSTALL_WEB_SERVER" "$INSTALL_WEB_SERVER"
 [ -n "${INSTALL_WEB_INTERFACE}" ] && change_setting "INSTALL_WEB_INTERFACE" "$INSTALL_WEB_INTERFACE"
 [ -n "${LIGHTTPD_ENABLED}" ] && change_setting "LIGHTTPD_ENABLED" "$LIGHTTPD_ENABLED"
+[ -n "${ServerIP}" ] && change_setting "IPV4_ADDRESS" "$ServerIP"
+[ -n "${ServerIPv6}" ] && change_setting "IPV6_ADDRESS" "$ServerIPv6"
 [ -n "${ServerIP}" ] && changeFTLsetting "REPLY_ADDR4" "$ServerIP"
 [ -n "${ServerIPv6}" ] && changeFTLsetting "REPLY_ADDR6" "$ServerIPv6"
 [ -n "${DNS_BOGUS_PRIV}" ] && change_setting "DNS_BOGUS_PRIV" "$DNS_BOGUS_PRIV"
```
HTH,
Matteo

**Comment by scara** [comment]
> I'm not familiar with the Pi-hole code but the recent changes suggest to me something like:

> and to avoid regressions on past configurations I suggest to restore even:

Forgive my ignorance 😉 !
Found https://github.com/pi-hole/pi-hole/pull/4131 and https://github.com/pi-hole/PADD/pull/161 which suggest to me to avoid re-adding `IPv*_ADDRESS`:
``` diff
diff --git a/install.sh b/install.sh
index e608807..a8a1c53 100644
--- a/install.sh
+++ b/install.sh
@@ -51,8 +51,6 @@ echo "${FTL_VERSION}" > /etc/pihole/ftlbranch
 # Preseed variables to assist with using --unattended install
 {
   echo "PIHOLE_INTERFACE=eth0"
-  echo "IPV4_ADDRESS=0.0.0.0"
-  echo "IPV6_ADDRESS=0:0:0:0:0:0"
   echo "PIHOLE_DNS_1=8.8.8.8"
   echo "QUERY_LOGGING=true"
   echo "INSTALL_WEB_SERVER=true"
diff --git a/start.sh b/start.sh
index 603cec3..fd88492 100755
--- a/start.sh
+++ b/start.sh
@@ -72,7 +72,6 @@ validate_env || exit 1
 prepare_configs

 [ -n "${PIHOLE_INTERFACE}" ] && change_setting "PIHOLE_INTERFACE" "$PIHOLE_INTERFACE"
-[ -n "${IPV4_ADDRESS}" ] && change_setting "IPV4_ADDRESS" "$IPV4_ADDRESS"
 [ -n "${INSTALL_WEB_SERVER}" ] && change_setting "INSTALL_WEB_SERVER" "$INSTALL_WEB_SERVER"
 [ -n "${INSTALL_WEB_INTERFACE}" ] && change_setting "INSTALL_WEB_INTERFACE" "$INSTALL_WEB_INTERFACE"
 [ -n "${LIGHTTPD_ENABLED}" ] && change_setting "LIGHTTPD_ENABLED" "$LIGHTTPD_ENABLED"
diff --git a/test/test_volume_data.sh b/test/test_volume_data.sh
index f82a8e4..ba84005 100755
--- a/test/test_volume_data.sh
+++ b/test/test_volume_data.sh
@@ -64,19 +64,16 @@ EXEC $CONTAINER /start.sh  # run all the startup scripts
 # Then default are present
 grep "PIHOLE_DNS_1=8.8.8.8" "$VOL_PH/setupVars.conf"
 grep "PIHOLE_DNS_2=8.8.4.4" "$VOL_PH/setupVars.conf"
-grep "IPV4_ADDRESS=0.0.0.0" "$VOL_PH/setupVars.conf"
 grep -E "WEBPASSWORD=.+" "$VOL_PH/setupVars.conf"

 # Given the settings are manually changed (not good settings, just for testing changes)
 EXEC $CONTAINER 'pihole -a setdns 127.1.1.1,127.2.2.2,127.3.3.3,127.4.4.4'
-EXEC $CONTAINER '. /opt/pihole/webpage.sh ; change_setting IPV4_ADDRESS 10.0.0.0'
 EXEC $CONTAINER 'pihole -a -p login'
 assert_new_settings() {
     grep "PIHOLE_DNS_1=127.1.1.1" "$VOL_PH/setupVars.conf"
     grep "PIHOLE_DNS_2=127.2.2.2" "$VOL_PH/setupVars.conf"
     grep "PIHOLE_DNS_3=127.3.3.3" "$VOL_PH/setupVars.conf"
     grep "PIHOLE_DNS_4=127.4.4.4" "$VOL_PH/setupVars.conf"
-    grep "IPV4_ADDRESS=10.0.0.0" "$VOL_PH/setupVars.conf"
     grep "WEBPASSWORD=6060d59351e8c2f48140f01b2c3f3b61652f396c53a5300ae239ebfbe7d5ff08" "$VOL_PH/setupVars.conf"
     grep "server=127.1.1.1" $VOL_DM/01-pihole.conf
     grep "server=127.2.2.2" $VOL_DM/01-pihole.conf
```
If it will look sane, it would be something for a separate issue, far from the simple documentation issue above.

HTH,
Matteo

**Comment by PromoFaux** [comment]
I've currently disabled the test that calls `/test/test_volume_data.sh` because I broke it in my latest changes to get the version correct in the footer/metadata, but I couldn't work out how to fix it 🤫

**Comment by shaderecker** [comment]
The REPLY_ADDR4 & REPLY_ADDR6 variables (in pihole/pihole-FTL.conf) are overwritten by ServerIP & ServerIPv6 at every container restart.
So I think users should stick to the existing ServerIP/ServerIPv6 variables.

**Comment by shaderecker** [comment]
This got addressed in #944

**Comment by scara** [comment]
Hi @shaderecker,
> This got addressed in #944

Thanks for the hint.

> Set to your server's LAN IP, used by web block modes and lighttpd bind address.

Do you think it will be enough to understand the underline impact even on `FTL REPLY` like it was described in https://github.com/pi-hole/docker-pi-hole/pull/902?
The ENV VAR name tells about that impact while the description is still the same.

TIA,
Matteo

**Comment by shaderecker** [comment]
Hi @scara, From a user perspective there should not be much difference, just the changed variable name. So yes I think it is enough.
Cheers, Sebastian

**Comment by scara** [comment]
Closed based on https://github.com/pi-hole/docker-pi-hole/issues/919#issuecomment-991963167.
